const NOTIFICATION_TYPES = {
  TRANSFER: 'TRANSFER',
  DEPOSIT: 'DEPOSIT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  ALERT: 'ALERT',
  EMAIL: 'EMAIL',
  CONFIRMATION: 'CONFIRMATION',
};

module.exports = { NOTIFICATION_TYPES };
